/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafetracker;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP Nav
 */
public class Categories extends javax.swing.JFrame {
    CategoryModel categoryModel = new CategoryModel();
    Boolean isUpdate = false;
    SingletonClass singletonClass = SingletonClass.getInstance();
    ArrayList<CategoryModel> categoryList = new ArrayList<>();

    /**
     * Creates new form Categories
     */
   void getCategoryList(){
       String[] header = {"id","Category Name"};
       //DefaultTableModel model = new DefaultTableModel(null,header);
       try{
          Statement statement = singletonClass.connection.createStatement();
           ResultSet result = statement.executeQuery("SELECT * FROM category");
       DefaultTableModel model = new DefaultTableModel(null,header);
        categoryTable.setModel(model);
        model.setRowCount(0);
        Object[] row = new Object[3];
         while(result.next()){
            categoryList.add(new CategoryModel(result.getInt("id"), result.getString("name")));
        }
         for (CategoryModel item : categoryList) {
                System.out.println(item);
                row[0] = item.getId();
                row[1] = item.getName();
                model.addRow(row);
            }
       }catch(SQLException sqlException){
       System.out.println("sqlException "+ sqlException);
      }
    }
    public Categories() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        tfCategoryName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAddCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        categoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(categoryTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 10, 375, 275);
        getContentPane().add(tfCategoryName);
        tfCategoryName.setBounds(20, 80, 160, 40);

        jLabel1.setText("Add Categories");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 100, 30);

        btnAddCategory.setText("Add");
        btnAddCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCategoryMouseClicked(evt);
            }
        });
        getContentPane().add(btnAddCategory);
        btnAddCategory.setBounds(40, 130, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCategoryMouseClicked
        // TODO add your handling code here:
        if(tfCategoryName.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Enter Category");
        }else{
            try{
            String insertCategory = "INSERT INTO category(name) VALUES(?)"; 
            PreparedStatement statement = singletonClass.connection.prepareCall(insertCategory);
            statement.setString(1,tfCategoryName.getText().toString());
             int insertData = statement.executeUpdate();
               // if(insertData > 0){
                System.out.println("Print Data");
                getCategoryList();
            }
            catch(SQLException sqlException){
            System.out.println("sqlException"+sqlException.getMessage());
            }
        }
    }//GEN-LAST:event_btnAddCategoryMouseClicked

    private void categoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel)categoryTable.getModel();
        int selectRow = categoryTable.getSelectedRow();
        String id = model.getValueAt(selectRow, 0).toString();
         System.out.println("id " +id);
        UpdateCategory update = new UpdateCategory(Integer.valueOf(id));
        update.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_categoryTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JTable categoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfCategoryName;
    // End of variables declaration//GEN-END:variables
}
