/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafetracker;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class Product extends javax.swing.JFrame {
    SingletonClass singletonClass = SingletonClass.getInstance();

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfProductName1 = new javax.swing.JTextField();
        tfDescription = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("         Add Product");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 130, 40);
        getContentPane().add(tfPrice);
        tfPrice.setBounds(10, 170, 150, 30);

        btnAddProduct.setText("Add Product");
        btnAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProductMouseClicked(evt);
            }
        });
        getContentPane().add(btnAddProduct);
        btnAddProduct.setBounds(30, 220, 110, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 10, 450, 360);

        tfProductName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductName1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfProductName1);
        tfProductName1.setBounds(10, 90, 150, 30);
        getContentPane().add(tfDescription);
        tfDescription.setBounds(10, 130, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProductMouseClicked
        // TODO add your handling code here:
        if(tfProductName1.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Product");
    }else if(tfDescription.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Description");
    }else if(tfPrice.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter Price");
    }else{
        try{
            String insertProduct = "INSERT INTO product(name,description,price) VALUES(?,?,?)"; 
            PreparedStatement statement = singletonClass.connection.prepareCall(insertProduct);
            statement.setString(1,tfProductName1.getText().toString());
            statement.setString(2,tfDescription.getText().toString());
            statement.setString(3,tfPrice.getText().toString());
            statement.executeUpdate();
               // if(insertData > 0){
                System.out.println("Print Data");
               
        }catch(SQLException sqlException){
            System.out.println("sqlException"+sqlException.getMessage());
        }
        }
    }//GEN-LAST:event_btnAddProductMouseClicked

    private void tfProductName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProductName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfProductName1;
    // End of variables declaration//GEN-END:variables
}
