/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafetracker;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class UpdateProduct extends javax.swing.JFrame {
    ProductModel productModel = new ProductModel();
    SingletonClass singletonClass = SingletonClass.getInstance();

    /**
     * Creates new form UpdateProduct
     */
    public UpdateProduct() {
        initComponents();
      
    }
   
    
    public UpdateProduct(int id){
        String updateData = "SELECT * FROM product where id="+id;
        
        try{
             PreparedStatement ps = singletonClass.connection.prepareCall(updateData);
            ResultSet result = ps.executeQuery();
            while(result.next()){
            productModel.setId(result.getInt("id"));
            productModel.setName(result.getString("name"));
            productModel.setDescription(result.getString("description"));
            productModel.setPrice(result.getDouble("price"));
            }
            
        }catch(SQLException sqlException){
            System.out.println("sqlException "+sqlException);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfProductName = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfProductPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfProductDescription = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAddProduct1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("     Update Product");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 30, 150, 21);

        tfProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfProductName);
        tfProductName.setBounds(170, 150, 190, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 70, 190, 30);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 110, 190, 30);

        jLabel3.setText("Select Category :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 71, 140, 30);

        jLabel4.setText("Price :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 260, 140, 30);

        tfProductPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductPriceActionPerformed(evt);
            }
        });
        getContentPane().add(tfProductPrice);
        tfProductPrice.setBounds(170, 250, 190, 40);

        jLabel5.setText("Product Name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 130, 30);

        tfProductDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProductDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(tfProductDescription);
        tfProductDescription.setBounds(170, 200, 190, 40);

        jLabel6.setText("Product Description :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 140, 30);

        btnAddProduct1.setText("Update Product");
        btnAddProduct1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProduct1MouseClicked(evt);
            }
        });
        getContentPane().add(btnAddProduct1);
        btnAddProduct1.setBounds(110, 320, 150, 40);

        jButton1.setText("Delete");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 380, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProductNameActionPerformed

    private void tfProductPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProductPriceActionPerformed

    private void tfProductDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProductDescriptionActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_tfProductDescriptionActionPerformed

    private void btnAddProduct1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProduct1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProduct1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String deleteCategory = "DELETE FROM product where id = ?";
        try{
            PreparedStatement ps = singletonClass.connection.prepareCall(deleteCategory);
            ps.setInt(1,productModel.getId());
            ps.executeUpdate();
              //  if (rowsInserted > 0) {
                    System.out.println("A product is deleted");
                    Categories categories = new Categories();
                    categories.setVisible(true);
                    this.dispose();
               // }
                    
        }catch(SQLException sqlException){
            System.out.println("sqlException "+sqlException.getMessage());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tfProductDescription;
    private javax.swing.JTextField tfProductName;
    private javax.swing.JTextField tfProductPrice;
    // End of variables declaration//GEN-END:variables
}
